version: "3.8"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend/:/app/
    ports:
      - 8000:8000
    networks:
      - back
  rand:
    build:
      context: ./rand
      dockerfile: Dockerfile.dev
    container_name: rand
    volumes:
      - ./rand/:/usr/src/app/
    restart: always
    networks:
      - back
    ports:
      - 6000:6000
    depends_on:
      - backend

networks:
  back:
    driver: bridge
