version: '3'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    network_mode: backend_repo_back

