FROM nginx:latest
RUN mkdir /app
COPY /dist /app

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/dev/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080 80 443 8000 6000
CMD ["nginx", "-g", "daemon off;"]
