version: '3'

services:
  frontend:
    container_name: frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/prod/certbot/conf:/etc/letsencrypt
      - ./nginx/prod/certbot/www:/var/www/certbot
      - ./dist:/app/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    network_mode: backend_repo_back

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/prod/certbot/prod/conf:/etc/letsencrypt
      - ./nginx/prod/certbot/prod/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
